### ISSUE TITLE
make clean all run doesn't work

### ISSUE THREAD

**Issue by luigifeola** [pulp-platform/pulp-detector#2]
Hi, I am trying the _gap8_app_ on my crazyflie.
I run the _gap_sdk_ starting from the `bitcraze/ai-deck` Dockerfile, installing conda and creating a new environment as described in the readme. However once I run `make clean all run` I got the following error: 
```
(tensorflow1.15) root@ccd230dd8ad7:/pulp-detector/gap8_app# make clean all run
Building GAP8 mode with 8 bit quantization
rm -rf BUILD*
rm -f /pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV/flash.img
make -f ssd.mk model CLUSTER_STACK_SIZE=4096 CLUSTER_SLAVE_STACK_SIZE=1024
make[1]: Entering directory '/pulp-detector/gap8_app'
Building GAP8 mode with 8 bit quantization
ssd.mk:56: *** empty variable name.  Stop.
make[1]: Leaving directory '/pulp-detector/gap8_app'
Makefile:104: recipe for target 'BUILD_MODEL_SSD/ssdlite_ocrKernels.c' failed
make: *** [BUILD_MODEL_SSD/ssdlite_ocrKernels.c] Error 2
```

Note:
1. Since there is no `4.7` version available from `bitcraze/ai-deck`, I tried both the `4.0.0`  and `4.8.0`, but the error I got is the same in both versions.
2. Since I am using the Olimex ARM-USB-TINY-H programmer I run `export GAPY_OPENOCD_CABLE=interface/ftdi/olimex-arm-usb-tiny-h.cfg`, but I don't think this can be related to the error since the helloworld example works. 

Have you ever experienced this type of error?

**Comment by LorenzoLamberti94** [comment]
havn't seen it, maybe @Bomps4 ?
i suggest anyways building the right gap sdk version (4.7) locally

**Comment by Bomps4** [comment]
Pushed solution the error was an unresolved merge at like 56 of ssd.mk

**Comment by luigifeola** [comment]
Hi @Bomps4 ,
Thank you for the fix! I tried the repo after applying it and installing the correct version of `gap_sdk` (4.7.0). 

To get the code building correctly, I made the following adjustments:

1. I updated the `gap_sdk` path at [here](https://github.com/pulp-platform/pulp-detector/blob/9fe78d17ba44baef399874135904336c6781e11d/gap8_app/SSD_tin_can_bottle.c#L33). This was a minor tweak and not a big issue.
2. I added the path to the `frame_streamer` libraries in the Makefile using: 
```
APP_CFLAGS += -I$(GAP_SDK_HOME)/libs/frame_streamer/include
```
This resolved the following error:

``` 
In file included from SSD_tin_can_bottle.c:33:0:
/gap_sdk/libs/frame_streamer/include/tools/frame_streamer.h:21:10: fatal error: tools/services.h: No such file or directory
 #include <tools/services.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated. 
```
3. Despite these fixes, I encountered another issue when trying to test the pulp-detector. The following error occurred:
```
Graph constructor exited with an error 
Traceback (most recent call last):
  File "/gap_sdk/utils/gapy/gapy", line 162, in <module>
    main()
  File "/gap_sdk/utils/gapy/gapy", line 152, in main
    operationFunc(args, config, system)
  File "/gap_sdk/utils/gapy/run.py", line 184, in operationFunc
    raise RuntimeError('Runner has failed with value: %d' % status)
RuntimeError: Runner has failed with value: -1
make: *** [/gap_sdk/utils/rules/pulp_rules.mk:252: run] Error 1
```

This seems related directly to the `gap_sdk` repository. Have you encountered a similar issue before?

I’ve attached the full output (output.txt) in case it helps diagnose the problem further.

Thanks again for your efforts on this! Let me know if you need any additional details.

[output.txt](https://github.com/user-attachments/files/18412067/output.txt)

**Comment by luigifeola** [comment]
I tried also the following commands:
`make clean all`
`make flash`
`make run`

In the attached `outout.txt` you can see the output of the first two command wich seems that they were executed without any error, while the `make run` produces the following error:
```
(tensorflow1.15) root@28283e2690ef:/pulp-detector/gap8_app# make run
Building GAP8 mode with 8 bit quantization
gapy --target=ai_deck --platform=board --work-dir=/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS  --config-opt=**/flash/content/partitions/readfs/files=/pulp-detector/gap8_app/BUILD_MODEL_SSD/SSD_tin_can_bottle_L3_Flash_Const.dat   --config-opt=flash/content/partitions/readfs/files=/pulp-detector/gap8_app/BUILD_MODEL_SSD/SSD_tin_can_bottle_L3_Flash_Const.dat   run --exec-prepare --exec --binary=/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS/SSD_tin_can_bottle 
Launching execution with command:
gap8-openocd -d0 -c 'gdb_port disabled; telnet_port disabled; tcl_port disabled' -f interface/ftdi/olimex-arm-usb-tiny-h.cfg -f target/gap8revb.tcl -f tcl/jtag_boot_entry.tcl -c 'gap8_jtag_load_binary_and_start "/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS/SSD_tin_can_bottle" elf 0x1c000080'
Open On-Chip Debugger 0.10.0+dev-gb84d97ec4 (2025-01-13-10:04)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 0

DEPRECATED! use 'adapter speed' not 'adapter_khz'
DEPRECATED! use 'adapter driver' not 'interface'
TARGET create
0
GAP8 INIT TARGET
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
Loading binary through JTAG
Graph constructor exited with an error 
Traceback (most recent call last):
  File "/gap_sdk/utils/gapy/gapy", line 162, in <module>
    main()
  File "/gap_sdk/utils/gapy/gapy", line 152, in main
    operationFunc(args, config, system)
  File "/gap_sdk/utils/gapy/run.py", line 184, in operationFunc
    raise RuntimeError('Runner has failed with value: %d' % status)
RuntimeError: Runner has failed with value: -1
make: *** [/gap_sdk/utils/rules/pulp_rules.mk:252: run] Error 1
(tensorflow1.15) root@28283e2690ef:/pulp-detector/gap8_app# 
```

Do you know why the _gapy_ utils generates this error?

[output.txt](https://github.com/user-attachments/files/18455872/output.txt)

**Comment by luigifeola** [comment]
Hi @Bomps4, 

I tired also with a smaller L2 memory in [ssd.mk#L54](https://github.com/pulp-platform/pulp-detector/blob/9fe78d17ba44baef399874135904336c6781e11d/gap8_app/ssd.mk#L54) setting `MODEL_L2_MEMORY=220000`. 

The `make run` command never ends, blocking at:
```
Building GAP8 mode with 8 bit quantization
gapy --target=ai_deck --platform=board --work-dir=/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS  --config-opt=**/flash/content/partitions/readfs/files=/pulp-detector/gap8_app/BUILD_MODEL_SSD/SSD_tin_can_bottle_L3_Flash_Const.dat   --config-opt=flash/content/partitions/readfs/files=/pulp-detector/gap8_app/BUILD_MODEL_SSD/SSD_tin_can_bottle_L3_Flash_Const.dat   run --exec-prepare --exec --binary=/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS/SSD_tin_can_bottle 
Launching execution with command:
gap8-openocd -d0 -c 'gdb_port disabled; telnet_port disabled; tcl_port disabled' -f interface/ftdi/olimex-arm-usb-tiny-h.cfg -f target/gap8revb.tcl -f tcl/jtag_boot_entry.tcl -c 'gap8_jtag_load_binary_and_start "/pulp-detector/gap8_app/BUILD/GAP8_V2/GCC_RISCV_PULPOS/SSD_tin_can_bottle" elf 0x1c000080'
Open On-Chip Debugger 0.10.0+dev-gb84d97ec4 (2025-01-21-15:06)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 0

DEPRECATED! use 'adapter speed' not 'adapter_khz'
DEPRECATED! use 'adapter driver' not 'interface'
TARGET create
0
GAP8 INIT TARGET
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
Loading binary through JTAG
```

It returns the same error of the previous two comments once the command is manually stopped by `ctrl+c`

Do you have any idea?
